# Generated by Django 4.0.6 on 2022-07-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='amount',
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.SmallIntegerField(default=0, verbose_name='Price'),
        ),
    ]
