# Generated by Django 4.0.6 on 2022-07-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0003_order_amount_alter_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Quantity'),
        ),
    ]
