# Generated by Django 4.0.6 on 2022-07-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0004_remove_order_amount_products_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Quantity'),
        ),
    ]
