# Generated by Django 4.0.6 on 2022-07-19 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0002_alter_supplier_description_alter_supplier_name'),
        ('order_manager', '0006_order_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_manager.supplier'),
        ),
    ]
