# Generated by Django 4.0.6 on 2022-07-19 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0007_orderitem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 11, 47, 13, 447295), verbose_name='Delivery Date'),
        ),
    ]
