# Generated by Django 4.0.6 on 2022-07-18 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import supplier_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Supplier')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='MySupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=supplier_manager.models.default_mail, max_length=50, verbose_name='Email')),
                ('phone', models.CharField(default=supplier_manager.models.default_number, max_length=20, verbose_name='Phone Number')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_supplier', to='supplier_manager.supplier')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'My Supplier',
            },
        ),
    ]
