# Generated by Django 4.0.6 on 2022-07-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Supplier'),
        ),
    ]
